services:
  - type: web
    name: shl-recommender
    env: python
    buildCommand: pip install -r requirements.txt && python train_and_serialize.py
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONHASHSEED
        value: 0
      - key: PORT
        value: 8000

